using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VCSLogViewer
{
    public enum ThemeColor
    {
        Default,
        Dark1,
        Dark2
    }

    public enum DI96
    {
        DI_0, DI_1, DI_2, DI_3, DI_4, DI_5, DI_6, DI_7, DI_8, DI_9,
        DI_10, DI_11, DI_12, DI_13, DI_14, DI_15, DI_16, DI_17, DI_18, DI_19,
        DI_20, DI_21, DI_22, DI_23, DI_24, DI_25, DI_26, DI_27, DI_28, DI_29,
        DI_30, DI_31, DI_32, DI_33, DI_34, DI_35, DI_36, DI_37, DI_38, DI_39,
        DI_40, DI_41, DI_42, DI_43, DI_44, DI_45, DI_46, DI_47, DI_48, DI_49,
        DI_50, DI_51, DI_52, DI_53, DI_54, DI_55, DI_56, DI_57, DI_58, DI_59,
        DI_60, DI_61, DI_62, DI_63, DI_64, DI_65, DI_66, DI_67, DI_68, DI_69,
        DI_70, DI_71, DI_72, DI_73, DI_74, DI_75, DI_76, DI_77, DI_78, DI_79,
        DI_80, DI_81, DI_82, DI_83, DI_84, DI_85, DI_86, DI_87, DI_88, DI_89,
        DI_90, DI_91, DI_92, DI_93, DI_94, DI_95
    }

    public enum DO96
    {
        DO_0, DO_1, DO_2, DO_3, DO_4, DO_5, DO_6, DO_7, DO_8, DO_9,
        DO_10, DO_11, DO_12, DO_13, DO_14, DO_15, DO_16, DO_17, DO_18, DO_19,
        DO_20, DO_21, DO_22, DO_23, DO_24, DO_25, DO_26, DO_27, DO_28, DO_29,
        DO_30, DO_31, DO_32, DO_33, DO_34, DO_35, DO_36, DO_37, DO_38, DO_39,
        DO_40, DO_41, DO_42, DO_43, DO_44, DO_45, DO_46, DO_47, DO_48, DO_49,
        DO_50, DO_51, DO_52, DO_53, DO_54, DO_55, DO_56, DO_57, DO_58, DO_59,
        DO_60, DO_61, DO_62, DO_63, DO_64, DO_65, DO_66, DO_67, DO_68, DO_69,
        DO_70, DO_71, DO_72, DO_73, DO_74, DO_75, DO_76, DO_77, DO_78, DO_79,
        DO_80, DO_81, DO_82, DO_83, DO_84, DO_85, DO_86, DO_87, DO_88, DO_89,
        DO_90, DO_91, DO_92, DO_93, DO_94, DO_95
    }

    public enum CMZ_INPUT_CHJS
    {
        UBG01_DETECT_01,
        UBG01_DETECT_02,
        UBG01_DETECT_03,
        UBG01_DETECT_04,
        UBG02_DETECT_01,
        UBG02_DETECT_02,
        UBG02_DETECT_03,
        UBG02_DETECT_04,
        LOOKDOWN_DETECT_01,
        LOOKDOWN_DETECT_02,
        LOOKDOWN_DETECT_03,
        LOOKDOWN_DETECT_04,
        BUMPER_OK,
        BUMPER_Alarm,
        EMO_SWITCH,
        DI_15,

        STEER_FRONT_LEFT,
        STEER_FRONT_RIGHT,
        DI_18,
        SYSTEM_DRV_STOP,
        TRANS_DRV_DET,
        TRANS_DRV_STOP,
        ANTIDROP_FRONT_LOCK,
        ANTIDROP_FRONT_UNLOCK,
        OUTRIGGER_FRONT_LOCK,
        OUTRIGGER_FRONT_UNLOCK,
        DI_26,
        SLIDE_HOME,
        DI_28,
        FOUP_DET,
        SWING_DETECT,
        HOIST_HOME,

        PCOM_1_POSITION,
        PCOM_2_STEP_ERROR,
        PCOM_3_LEFT_FLANGE,
        PCOM_4_RIGHT_FLANGE,
        PCOM_5_GRIP,
        PCOM_6_UNGRIP,
        PCOM_7_PUSHER,
        PCOM_8_,
        PCOM_ES,
        PCOM_STEP_GO,
        ZCU_01,
        ZCU_02,
        ZCU_03,
        ZCU_04,
        ZCU_05,
        ZCU_06,

        STEER_REAR_LEFT,
        STEER_REAR_RIGHT,
        ANTIDROP_REAR_LOCK,
        ANTIDROP_REAR_UNLOCK,
        OUTRIGGER_REAR_LOCK,
        OUTRIGGER_REAR_UNLOCK,
        DI_54,
        DI_55,
        FOUP_OPEN_DETECT,
        STB_LEFT_DET,
        DI_58,
        DI_59,
        DI_60,
        DI_62,
        DI_63,
        DI_64,

        EQ_PIO_1_L_REQ,
        EQ_PIO_2_U_REQ,
        EQ_PIO_3,
        EQ_PIO_4_READY,
        EQ_PIO_5,
        EQ_PIO_6,
        EQ_PIO_7_HO_AVBL,
        EQ_PIO_8_ES,
        EQ_PIO_9_PIO_GO,
        DI_73,
        DI_74,
        DI_75,
        DI_76,
        DI_77,
        DI_78,
        DI_79
    }

    public enum CMZ_OUTPUT_CHJS
    {
        DO_0,
        BRAKE_DRIVE,
        BRAKE_HOIST,
        MAIN_MC,
        UBG01_AREA_01,
        UBG01_AREA_02,
        UBG01_AREA_03,
        UBG01_AREA_04,
        UBG02_AREA_01,
        UBG02_AREA_02,
        UBG02_AREA_03,
        UBG02_AREA_04,
        LOOKDOWN_AREA_01,
        LOOKDOWN_AREA_02,
        LOOKDOWN_AREA_03,
        LOOKDOWN_AREA_04,

        STEER_FRONT_LEFT,
        STEER_FRONT_RIGHT,
        STEER_REAR_LEFT,
        STEER_REAR_RIGHT,
        TRACTION_STEER_FRONT_LEFT,
        TRACTION_STEER_FRONT_RIGHT,
        TRACTION_STEER_REAR_LEFT,
        TRACTION_STEER_REAR_RIGHT,

        ANTIDROP_START,
        ANTIDROP_CW_CCW,
        OUTRIGGER_FRONT_START,
        OUTRIGGER_FRONT_CW_CCW,
        DO_28,
        DO_29,
        DO_30,
        DO_31,
        ZCU_01,
        ZCU_02,
        ZCU_03,
        ZCU_04,
        ZCU_05,
        ZCU_06,
        DO_38,
        DO_39,

        PCOM_01_GRIP,
        PCOM_02_UNGRIP,
        PCOM_03_HOME,
        PCOM_04_RESET,
        PCOM_05_FREE,
        PCOM_06_CBRK_RELEASE,
        PCOM_07_TEACHING,
        PCOM_08,
        PCOM_TRIGGER,
        PCOM_SELECT,
        PCOM_MODE,
        DO_51,
        DO_52,
        DO_53,
        DO_54,
        DO_55,

        LED_LAMP_RED,
        LED_LAMP_GREEN,
        LED_LAMP_BLUE,
        BUZZER_1,
        BUZZER_2,
        BUZZER_3,
        BUZZER_4,
        DO_63,
        ANTIDROP_REAR_START,
        ANTIDROP_REAR_CW_CCW,
        OUTRIGGER_REAR_START,
        OUTRIGGER_REAR_CW_CCW,
        DO_68,
        BUMPER_RESET,
        DO_70,
        DO_71,

        EQ_PIO_01_VALID,
        EQ_PIO_02_CS,
        EQ_PIO_03,
        EQ_PIO_04,
        EQ_PIO_05_TR_REQ,
        EQ_PIO_06_BUSY,
        EQ_PIO_07_COMPT,
        EQ_PIO_08,
        EQ_PIO_09_SELECT,
        DO_81,
        DO_82,
        DO_83,
        DO_84,
        DO_85,
        DO_86,
        DO_87
    }

    public enum CMZ_INPUT_WUXI
    {
        UBG01_DETECT_01,
        UBG01_DETECT_02,
        UBG01_DETECT_03,
        UBG01_DETECT_04,
        UBG02_DETECT_01,
        UBG02_DETECT_02,
        UBG02_DETECT_03,
        UBG02_DETECT_04,
        LOOKDOWN_DETECT_01,
        LOOKDOWN_DETECT_02,
        LOOKDOWN_DETECT_03,
        LOOKDOWN_DETECT_04,
        BUMPER_OK,
        BUMPER_Alarm,
        EMO_SWITCH,
        DI_15,
        STEER_FRONT_LEFT,
        STEER_FRONT_RIGHT,
        DI_18,
        SYSTEM_DRV_STOP,
        DI_20,
        DI_21,
        ANTIDROP_F_LOCK,
        ANTIDROP_F_UNLOCK,
        DI_24,
        DI_25,
        DI_26,
        SLIDE_HOME,
        DI_28,
        FOUP_DET,
        SWING_DETECT,
        HOIST_HOME,
        PCOM_1_POSITION,
        PCOM_2_STEP_ERROR,
        PCOM_3_LEFT_FLANGE,
        PCOM_4_RIGHT_FLANGE,
        PCOM_5_GRIP,
        PCOM_6_UNGRIP,
        PCOM_7_PUSHER,
        PCOM_8_,
        PCOM_ES,
        PCOM_STEP_GO,
        DI_42,
        DI_43,
        DI_44,
        DI_45,
        DI_46,
        DI_47,
        STEER_REAR_LEFT,
        STEER_REAR_RIGHT,
        ANTIDROP_R_LOCK,
        ANTIDROP_R_UNLOCK,
        DI_52,
        DI_53,
        DI_54,
        DI_55,
        DI_56,
        DI_57,
        DI_58,
        DI_59,
        EQ_QR_DETECT,
        DI_61,
        DI_62,
        DI_63,
        EQ_PIO_1_L_REQ,
        EQ_PIO_2_U_REQ,
        EQ_PIO_3,
        EQ_PIO_4_READY,
        EQ_PIO_5,
        EQ_PIO_6,
        EQ_PIO_7_HO_AVBL,
        EQ_PIO_8_ES,
        EQ_PIO_9_PIO_GO,
        DI_73,
        DI_74,
        DI_75,
        DI_76,
        DI_77,
        DI_78,
        DI_79,
        ROTATE_PLUS_LIMIT,
        ROTATE_HOME,
        ROTATE_MINUS_LIMIT
    }

    public enum CMZ_OUTPUT_WUXI
    {
        DO_0,
        BRAKE_DRIVE,
        BRAKE_HOIST,
        MAIN_MC,
        UBG01_AREA_01,
        UBG01_AREA_02,
        UBG01_AREA_03,
        UBG01_AREA_04,
        UBG02_AREA_01,
        UBG02_AREA_02,
        UBG02_AREA_03,
        UBG02_AREA_04,
        LOOKDOWN_AREA_01,
        LOOKDOWN_AREA_02,
        LOOKDOWN_AREA_03,
        LOOKDOWN_AREA_04,
        STEER_FRONT_LEFT,
        STEER_FRONT_RIGHT,
        STEER_REAR_LEFT,
        STEER_REAR_RIGHT,
        DO_20,
        DO_21,
        DO_22,
        DO_23,
        DO_24,
        DO_25,
        DO_26,
        DO_27,
        DO_28,
        DO_29,
        DO_30,
        DO_31,
        DO_32,
        DO_33,
        DO_34,
        DO_35,
        DO_36,
        DO_37,
        DO_38,
        DO_39,
        PCOM_01_GRIP,
        PCOM_02_UNGRIP,
        PCOM_03_HOME,
        PCOM_04_RESET,
        PCOM_05_FREE,
        PCOM_06_CBRK_RELEASE,
        PCOM_07_TEACHING,
        PCOM_08,
        PCOM_TRIGGER,
        PCOM_SELECT,
        PCOM_MODE,
        DO_51,
        DO_52,
        DO_53,
        DO_54,
        DO_55,
        REAR_LED_LAMP_RED,
        REAR_LED_LAMP_GREEN,
        REAR_LED_LAMP_BLUE,
        BUZZER_1,
        BUZZER_2,
        BUZZER_3,
        BUZZER_4,
        DO_63,
        DO_64,
        DO_65,
        DO_66,
        DO_67,
        DO_68,
        BUMPER_RESET,
        DO_70,
        DO_71,
        EQ_PIO_01_VALID,
        EQ_PIO_02_CS,
        EQ_PIO_03_CS_11,
        EQ_PIO_04,
        EQ_PIO_05_TR_REQ,
        EQ_PIO_06_BUSY,
        EQ_PIO_07_COMPT,
        EQ_PIO_08_CONT,
        EQ_PIO_09_SELECT,
        DO_81,
        DO_82,
        DO_83,
        DO_84,
        DO_85,
        DO_86,
        DO_87
    }
}
